pipeline:
  identifier: Build_Subhya090_binaryudp_1741606998488
  name: Build binaryudp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1741606939087
        repoName: Subhya090/binaryudp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: setup_dropbear_ngrok
                  name: Setup Dropbear SSH  Ngrok
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "🔹 Updating system and installing Dropbear SSH..."
                      apt-get update && apt-get install -y dropbear wget unzip curl

                      echo "🔹 Creating SSH user 'samir' with password 'samir090'..."
                      useradd -m -s /bin/bash samir
                      echo 'samir:samir090' | chpasswd

                      echo "🔹 Configuring Dropbear to run on port 3434..."
                      echo "DROPBEAR_EXTRA_ARGS='-p 3434'" > /etc/default/dropbear
                      service dropbear restart

                      echo "🔹 Checking if Dropbear is running..."
                      netstat -tlnp | grep 3434 || echo "❌ Dropbear failed to start!"

                      echo "🔹 Downloading & installing Ngrok..."
                      wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
                      unzip /tmp/ngrok.zip -d /usr/local/bin/
                      chmod +x /usr/local/bin/ngrok

                      echo "🔹 Authenticating Ngrok..."
                      ngrok authtoken 2lKjA15AAL3kFG0cbOpfTJGbewT_3PjMCSs55KCHQ2PKkoVdS

                      echo "🔹 Starting Ngrok to expose Dropbear SSH on port 3434..."
                      nohup ngrok tcp 3434 > /dev/null 2>&1 &

                      echo "🔹 Waiting for Ngrok tunnel to be established..."
                      sleep 10


                      echo "🔹 Keeping build alive for 40 hours..."
                      sleep 144000
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            size: xlarge
            type: Cloud
        type: CI
  timeout: 53w
